#!/bin/bash

sudo install -m 0755 system-updates/update-bce-docs /usr/local/bin/
sudo /usr/local/bin/update-bce-docs
sudo apt-get update
sudo apt-get install -y ruby2.1 ruby2.1-dev bundler
(cd /tmp; \
 rm -f vagrant_1.7.2_x86_64.deb; \
 wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb; \
 sudo dpkg -i vagrant_1.7.2_x86_64.deb; \
)
vagrant plugin install vagrant-aws
vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
