Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "YOUR_KEY_HERE"
    aws.secret_access_key = "SECRET_ACCESS_KEY"

    aws.ami = "ami-cdf5d3fd"        # BCE-2015-spring

    aws.instance_type = t2.micro    # $0.013/hr, 1 vCPU, 1GB RAM
    #aws.instance_type = t2.small    # $0.026/hr, 1 vCPU, 2GB RAM
    #aws.instance_type = t2.medium   # $0.052/hr, 2 vCPU, 4GB RAM

    ################################################################
    #### DON'T CHANGE the configuration below this line
    ################################################################
    aws.region = "us-west-2"
    aws.keypair_name = "student1@berkeley.edu:cloud101-spring-2015"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/cloud101-spring-2015-ssh_key.pem"
  end
end
